### ISSUE TITLE
hCaptcha doesn't appear on Chrome based browers

### ISSUE THREAD

**Issue by DeepakPaswan12** [tarator/hcaptcha-response-generator#1]
![image](https://user-images.githubusercontent.com/91746542/215241472-7a3e5f6a-5470-483f-bb0d-e86839897fb7.png)

**Comment by tarator** [comment]
New version deployed on https://hcaptcha.projecttac.com
Works now also for Chrome-based Browsers

**Comment by tarator** [comment]
@deepakkumar132 please let me know if it works for you now. Thanks for the effort reporting this issue <3 . I wouldn't have noticed for quite some time.
